/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fooddesk;

import java.awt.Font;
import java.awt.font.TextAttribute;
import java.sql.SQLException;
import java.util.Map;


public class LoginFrame extends javax.swing.JFrame {
    private String userInputPlaceholder = "Usuario";
    private String passwordInputPlaceholder = "---------";

    public LoginFrame() {
        initComponents();
        this.setFontEffects();
        this.setPlaceholders();
        this.hideComponents();
    }
    
    private void hideComponents(){
        this.errorLabel.setVisible(false);
    }
    
    private void setFontEffects(){
        Font forgotPasswordFont = this.forgotPasswordLabel.getFont();
        Map forgotPasswordAttributes = forgotPasswordFont.getAttributes();
        forgotPasswordAttributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        this.forgotPasswordLabel.setFont(forgotPasswordFont.deriveFont(forgotPasswordAttributes));
        
        Font registerFont = this.registerLabel.getFont();
        Map registerAttributes = registerFont.getAttributes();
        registerAttributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        this.registerLabel.setFont(registerFont.deriveFont(registerAttributes));
    }
    
    private void setPlaceholders(){
        this.userInput.setText(this.userInputPlaceholder);
        this.passwordInput.setText(this.passwordInputPlaceholder);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        userInput = new javax.swing.JTextField();
        forgotPasswordLabel = new javax.swing.JLabel();
        registerLabel = new javax.swing.JLabel();
        acceptBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        passwordInput = new javax.swing.JPasswordField();
        errorLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel2.setText("Iniciar Sesión");

        userInput.setText("Usuario");
        userInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userInputMouseClicked(evt);
            }
        });
        userInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userInputActionPerformed(evt);
            }
        });

        forgotPasswordLabel.setForeground(new java.awt.Color(0, 0, 255));
        forgotPasswordLabel.setText("¿Olvidó su contraseña?");
        forgotPasswordLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forgotPasswordLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotPasswordLabelMouseClicked(evt);
            }
        });

        registerLabel.setForeground(new java.awt.Color(0, 0, 255));
        registerLabel.setText("Registro");
        registerLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerLabelMouseClicked(evt);
            }
        });

        acceptBtn.setText("Aceptar");
        acceptBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acceptBtnMouseClicked(evt);
            }
        });
        acceptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptBtnActionPerformed(evt);
            }
        });

        exitBtn.setText("Salir");
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnMouseClicked(evt);
            }
        });
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        passwordInput.setToolTipText("");
        passwordInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordInputMouseClicked(evt);
            }
        });

        errorLabel.setForeground(new java.awt.Color(255, 0, 0));
        errorLabel.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(forgotPasswordLabel)
                            .addComponent(registerLabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(78, 78, 78))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(userInput, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passwordInput, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(acceptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userInput, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordInput, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorLabel)
                .addGap(2, 2, 2)
                .addComponent(forgotPasswordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registerLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acceptBtn)
                    .addComponent(exitBtn))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userInputActionPerformed

    private void userInputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userInputMouseClicked
        if (this.userInput.getText().compareTo(this.userInputPlaceholder) == 0){
            this.userInput.setText("");
        }
        this.errorLabel.setVisible(false);
    }//GEN-LAST:event_userInputMouseClicked

    private void exitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitBtnMouseClicked

    private void forgotPasswordLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotPasswordLabelMouseClicked
        this.dispose();
        RecoverPasswordFrame frame = new RecoverPasswordFrame ();
        frame.setVisible(true);
    }//GEN-LAST:event_forgotPasswordLabelMouseClicked

    private void registerLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerLabelMouseClicked
        this.dispose();
        RegisterFrame frame = new RegisterFrame ();
        frame.setVisible(true);
    }//GEN-LAST:event_registerLabelMouseClicked
    
    private void showError(String error){
        this.errorLabel.setVisible(true);
        this.errorLabel.setText(error);
    }
    
    private void displayViewForProfile(String profile){
        if (profile == null){
            this.showError("Nombre de usuario o password incorrectos");
            return;
        }
        
        switch(profile.toLowerCase()){
            case "cliente":
                CustomerFrame customerFrame = new CustomerFrame();
                this.dispose();
                customerFrame.setVisible(true);
                break;
            case "administrador":
                AdministrationFrame adminFrame = new AdministrationFrame();
                this.dispose();
                adminFrame.setVisible(true);
                break;
            case "empleado":
                WorkerFrame workerFrame = new WorkerFrame();
                this.dispose();
                workerFrame.setVisible(true);
                break;
            default:
                this.acceptBtn.setEnabled(true);
                this.showError("El perfil de tu usuario no es valido");
                break;
        }
    }
    
    private void acceptBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acceptBtnMouseClicked
        
    }//GEN-LAST:event_acceptBtnMouseClicked

    private void passwordInputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordInputMouseClicked
        this.passwordInput.setText("");
        this.errorLabel.setVisible(false);
    }//GEN-LAST:event_passwordInputMouseClicked

    private void acceptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptBtnActionPerformed
       try {
            this.acceptBtn.setEnabled(false);
            DatabaseHandler dbHandler = new DatabaseHandler();
            String user = this.userInput.getText();
            String password = this.passwordInput.getText();
            String profile = dbHandler.getUserProfile(user, password);
            this.displayViewForProfile(profile);
        } catch (SQLException ex) {
            this.showError("Error cargando datos");
        }
        finally{
            this.acceptBtn.setEnabled(true);
        }
    }//GEN-LAST:event_acceptBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptBtn;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel forgotPasswordLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField passwordInput;
    private javax.swing.JLabel registerLabel;
    private javax.swing.JTextField userInput;
    // End of variables declaration//GEN-END:variables
}
