CREATE TABLE ADMIN.CLIENTS 
    ( 
     RUT        NVARCHAR2 (10) , 
     NOMBRE     NVARCHAR2 (50)  NOT NULL , 
     APELLIDO   NVARCHAR2 (50)  NOT NULL , 
     MAIL       NVARCHAR2 (50)  NOT NULL , 
     USER_ID    NUMBER (*,0) 
         CONSTRAINT NNC_WORKERV1_USER_ID NOT NULL , 
     PROFILE_ID NUMBER (*,0) 
         CONSTRAINT NNC_WORKERV1_PROFILE_ID NOT NULL 
    ) 
    NO INMEMORY 
;


CREATE UNIQUE INDEX ADMIN.CLIENTS_PK ON ADMIN.CLIENTS 
    ( 
     RUT ASC 
    ) 
;

ALTER TABLE ADMIN.CLIENTS 
    ADD CONSTRAINT CLIENTS_PK PRIMARY KEY ( RUT ) 
    USING INDEX ADMIN.CLIENTS_PK ;

CREATE TABLE ADMIN.PROFILES 
    ( 
     PROFILE_ID  NUMBER (*,0) , 
     NAME        NVARCHAR2 (50)  NOT NULL , 
     DESCRIPTION NVARCHAR2 (100) 
    ) 
    NO INMEMORY 
;


CREATE UNIQUE INDEX ADMIN.PROFILES_PK ON ADMIN.PROFILES 
    ( 
     PROFILE_ID ASC 
    ) 
;

ALTER TABLE ADMIN.PROFILES 
    ADD CONSTRAINT PROFILES_PK PRIMARY KEY ( PROFILE_ID ) 
    USING INDEX ADMIN.PROFILES_PK ;

CREATE TABLE ADMIN.RESERVA 
    ( 
     ID_RESERVA    NUMBER (*,0) , 
     RUT_CLIENTE   NVARCHAR2 (10)  NOT NULL , 
     FECHA_RESERVA DATE  NOT NULL , 
     CANT_PERSONAS NUMBER (*,0)  NOT NULL , 
     MESA_ASIGNADA NUMBER (*,0)  NOT NULL 
    ) 
    NO INMEMORY 
;


CREATE UNIQUE INDEX ADMIN.RESERVA_PK ON ADMIN.RESERVA 
    ( 
     ID_RESERVA ASC 
    ) 
;

ALTER TABLE ADMIN.RESERVA 
    ADD CONSTRAINT RESERVA_PK PRIMARY KEY ( ID_RESERVA ) 
    USING INDEX ADMIN.RESERVA_PK ;

CREATE TABLE ADMIN.USERS 
    ( 
     USER_ID    NUMBER (*,0) , 
     USUARIO    NVARCHAR2 (50)  NOT NULL , 
     PASSWORD   NVARCHAR2 (50)  NOT NULL , 
     PROFILE_ID NUMBER (*,0)  NOT NULL 
    ) 
    NO INMEMORY 
;


CREATE UNIQUE INDEX ADMIN.USERS_PK ON ADMIN.USERS 
    ( 
     USER_ID ASC 
    ) 
;

ALTER TABLE ADMIN.USERS 
    ADD CONSTRAINT USERS_PK PRIMARY KEY ( USER_ID ) 
    USING INDEX ADMIN.USERS_PK ;

CREATE TABLE ADMIN.WORKER 
    ( 
     RUT        NVARCHAR2 (10) , 
     NOMBRE     NVARCHAR2 (50)  NOT NULL , 
     APELLIDO   NVARCHAR2 (50)  NOT NULL , 
     CARGO      NVARCHAR2 (50)  NOT NULL , 
     MAIL       NVARCHAR2 (50)  NOT NULL , 
     DIRECCION  NVARCHAR2 (50)  NOT NULL , 
     USER_ID    NUMBER (*,0)  NOT NULL , 
     PROFILE_ID NUMBER (*,0)  NOT NULL 
    ) 
    NO INMEMORY 
;


CREATE UNIQUE INDEX ADMIN.WORKER_PK ON ADMIN.WORKER 
    ( 
     RUT ASC 
    ) 
;

ALTER TABLE ADMIN.WORKER 
    ADD CONSTRAINT WORKER_PK PRIMARY KEY ( RUT ) 
    USING INDEX ADMIN.WORKER_PK ;

ALTER TABLE ADMIN.CLIENTS 
    ADD CONSTRAINT CLIENTS_PROFILES_FK FOREIGN KEY 
    ( 
     PROFILE_ID
    ) 
    REFERENCES ADMIN.PROFILES 
    ( 
         PROFILE_ID
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE ADMIN.CLIENTS 
    ADD CONSTRAINT CLIENTS_USERS_FK FOREIGN KEY 
    ( 
     USER_ID
    ) 
    REFERENCES ADMIN.USERS 
    ( 
         USER_ID
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE ADMIN.RESERVA 
    ADD CONSTRAINT RESERVA_CLIENTS_FK FOREIGN KEY 
    ( 
     RUT_CLIENTE
    ) 
    REFERENCES ADMIN.CLIENTS 
    ( 
         RUT
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE ADMIN.WORKER 
    ADD CONSTRAINT WORKER_PROFILES_FK FOREIGN KEY 
    ( 
     PROFILE_ID
    ) 
    REFERENCES ADMIN.PROFILES 
    ( 
         PROFILE_ID
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE ADMIN.WORKER 
    ADD CONSTRAINT WORKER_USERS_FK FOREIGN KEY 
    ( 
     USER_ID
    ) 
    REFERENCES ADMIN.USERS 
    ( 
         USER_ID
    ) 
    NOT DEFERRABLE 
;



